### ISSUE TITLE
Image dump won't work with jpg

### ISSUE THREAD

**Issue by promasu** [bcosca/fatfree#1043] opened 2017-06-09 14:06 UTC
Hi there,

I got a problem with my page. I have a image upload function and I scale the images with the Images class down. I then want to save the files via the dump() function for that. My imageformat ist jpeg. Like in the doku for 3.5 pointed out, I use ist with my class->dump('jpeg', 75)

It gets me the error: imagejpeg() [<a href='http://de.php.net/function.imagejpeg'>function.imagejpeg</a>]: Invalid 2nd parameter, it must a filename or a stream

**Comment by Rayne** [comment] 2017-06-10 13:14
I'm able to reproduce the issue with `3.5.0` and `3.5.1`. Please upgrade to `3.6.0` if possible. If there isn't anything left feel free to close the issue.

**Comment by promasu** [comment] 2017-06-10 13:41
It's the bug I have changed the documentary for. I was wondering, why the bug was not pointed out as fixed in the changelog for v3.6, so I've created #1044. I've searched the commits for the bugfix and I found it in the 3.6 release. Maybe the changelog should be changed afterwards.

**Comment by xfra35** [comment] 2017-06-12 10:12
This is a duplicate of https://github.com/bcosca/fatfree-core/issues/146.

Thanks for pointing out the docs deficiency on this.

Fixed in:
* https://github.com/bcosca/fatfree-core/commit/8e6886aade7096060237ccc6e8b955fa4b6515bb
* https://github.com/bcosca/fatfree/commit/835f53661a25eb46734a4fbaaef610385481eed2
* https://github.com/F3Community/F3com-data/commit/5236c0b524d0204a0ad7d3447d526e7a0cc5dae0

**Closed by xfra35** 2017-06-12 10:13 UTC
