### ISSUE TITLE
Unable to recover table name of mapped sql table

### ISSUE THREAD

**Issue by JeromeGill** [bcosca/fatfree#767] opened 2015-01-26 15:57 UTC
It is currently not possible to return the table name of a mapped SQL table which makes comparing two mapper objects computationally needlessly expensive and potentially flawed (you could compare the fields for example, but can't guarantee they are for the same table in actuality in edge cases where you have two tables with the same field names)

**Comment by ikkez** [comment] 2015-01-26 16:13
There is a method to return the table fields, see http://fatfreeframework.com/sql-mapper#schema

**Comment by JeromeGill** [comment] 2015-01-26 16:17
Sorry, I meant the table name. Updated the issue to reflect that! (need coffee! :smile:) As I said in the issue, you could return the fields and compare them but it is heavier than necessary.

**Comment by bcosca** [comment] 2015-01-28 15:45
Dupe of issue #768

**Closed by bcosca** 2015-01-28 15:45 UTC
Labels: duplicate
