### ISSUE TITLE
DB based sessions not working with version 3.6

### ISSUE THREAD

**Issue by johangm90** [bcosca/fatfree#980] opened 2016-11-25 19:38 UTC
`Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes}`

**Comment by ikkez** [comment] 2016-11-26 10:33
Regarding this [SO](http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes) question, your issue is about a column index in the session table. Since index handling is not built into the db session class, it's maybe about a custom unique index in your table? the only thing that has changed was the max column length for the var char columns

**Comment by ikkez** [comment] 2017-03-22 09:36
Closing this, because 3 months without a repy. Please reopen if the issue is this still valid.

**Closed by ikkez** 2017-03-22 09:36 UTC

**Comment by johangm90** [comment] 2017-05-21 06:13
i still getting that error i am using ubuntu 16.04 with mariadb 10

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes [***/vendor/bcosca/fatfree/lib/db/sql.php:227]

[***/vendor/bcosca/fatfree/lib/db/sql.php:227] PDOStatement->execute()
[***/vendor/bcosca/fatfree/lib/db/sql/session.php:188] DB\SQL->exec(['CREATE TABLE IF NOT EXISTS `sessions` (
	`session_id` VARCHAR(255),
	`data` TEXT,
	`ip` VARCHAR(45),
	`agent` VARCHAR(300),
	`stamp` INTEGER,
	PRIMARY KEY (`session_id`)
);'])
[***/app/controllers/Controller.php:45] DB\SQL\Session->__construct(DBSQL::__set_state([]),'sessions',true,Closure::__set_state([]))
[***/app/controllers/MainController.php:13] Controller->__construct()

**Comment by bcosca** [comment] 2017-05-21 23:06
@johangm90 UTF-16?

**Comment by johangm90** [comment] 2017-05-21 23:30
UTF8

**Comment by eliargon** [comment] 2018-08-14 15:33
Had the same problem.  Since my database is defined with collation of "utf8mb4_general_ci"
I fixed it by adding the default charset utf8 to the end of the creating sessions table.
Added in lib\db\sql\session.php in line 191
')DEFAULT CHARSET=utf8;'
