### ISSUE TITLE
Use of undefined constant RAW - assumed 'RAW'

### ISSUE THREAD

**Issue by noxtras** [bcosca/fatfree#1141] opened 2019-02-14 08:33 UTC
Hi,
In php 7.3 I get this: 

Use of undefined constant RAW - assumed 'RAW' (this will throw an Error in a future version of PHP)

When I use | RAW inside a template. I've downloaded the dec. 24 version and it still shows the error.

Thanks for the awesome framework.

**Comment by pauljherring** [comment] 2019-02-14 09:26
I can't reproduce it:

```
$ cat index.php
<?php
$f3 = require('f3/lib/base.php');
$f3->route('GET /',
    function($f3) {
                $f3->set('test', 'Hello <b>bold</b> world.');
                // echo deliberate_error;
                echo \Template::instance()->render('template.htm');
        });
$f3->run();
```

```
$ cat template.htm
PHP version: {{ phpversion() }}</br />
F3 version: {{ @VERSION}}<br />
Without raw: {{@test}}<br />
With raw: {{@test|raw}}<br />
With RAW: {{@test|RAW}}<br />
Deliberate error: {{@asdf}}<br />
```

```
$ curl -L http://hpdesktop.dontexist.com/f3
PHP version: 7.3.2-3+ubuntu18.10.1+deb.sury.org+1</br />
F3 version: 3.6.5-Release<br />
Without raw: Hello &lt;b&gt;bold&lt;/b&gt; world.<br />
With raw: Hello <b>bold</b> world.<br />
With RAW: Hello <b>bold</b> world.<br />
Deliberate error: <br />
```

The only time I can get the error is if I uncomment the `echo deliberate_error;` line:

```
$ curl -L http://hpdesktop.dontexist.com/f3
<!DOCTYPE html>
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Use of undefined constant deliberate_error - assumed 'deliberate_error' (this will throw an Error in a future version of PHP)</p>
</body>
</html>
$
```

**Comment by ikkez** [comment] 2019-02-14 16:05
@noxtras make sure when you write `@foo | RAW`, that the space between `|` and `raw` is a space char. I've encountered this some times when typing fast, that I accedentially hit `ALT + SPACE` on my mac after typing `ALT + 7` for the | pipe, and that's causing a half-space char instead of a real space, hence is looks for ` raw` as filter variable, which doesnt exist, is then untouched and treated as constant within the template.

**Comment by pauljherring** [comment] 2019-02-14 16:22
> the space between `|` and `raw` is a space char

Or don't have one there at all - just realised that's what my test above does...

**Comment by noxtras** [comment] 2019-02-14 16:44
wow. amazing community! it was that space. 
Thank you.

**Comment by Rayne** [comment] 2019-02-14 17:16
Don't forget to close the issue. :-)

**Closed** 2019-02-14 17:26 UTC
Labels: bogus / invalid
