### ISSUE TITLE
X-Sendfile

### ISSUE THREAD

**Issue by hmacube** [bcosca/fatfree#907] opened 2016-01-24 07:24 UTC
Hi
I have problem with X-Sendfile and FatFree

I run this code in native PHP without problem and I download file correctly
```php
        header('X-Sendfile: '.$filePath);
        header('Content-Type: '.$this->getMime());
        header('Content-Disposition: attachment; filename="'.time().'.'.$this->getExtension().'"');
```

But in FatFree , Alway I have this error
>
Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.
If you think this is a server error, please contact the webmaster.
Error 404
127.0.0.1
Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.2 
>

in both scenario $filePath is same and I am sure that I config X-SendFile correctly

Also I try to remove all FatFree Headers using this code
```php
        foreach(apache_response_headers() as $key=>$value)
            header_remove($key);
```
But same problem , 404 occured

**Comment by hmacube** [comment] 2016-02-01 05:43
Any idea?

**Comment by KOTRET** [comment] 2016-02-01 06:20
You are sure that the code is being executed? The 404 should not be caused by a file not found for sendfile but from the route not being found.

**Comment by hmacube** [comment] 2016-02-06 05:48
I'm sure that code is being executed , because
If I comment 
```php
// header('X-Sendfile: '.$filePath);
```
Download dialog opened and I can download 0 byte file

**Comment by hmacube** [comment] 2016-02-07 09:54
Please help me

**Comment by KOTRET** [comment] 2016-02-08 09:44
sounds like an issue with mod_xsendfile, probably the path is relative and not correct for the subdir of your app.
I don't use this extension, sorry

**Comment by xfra35** [comment] 2016-02-08 10:10
I was wondering what that `X-Sendfile` header stood for. @KOTRET is right. That's an issue with mod_xsendfile, not with the framework. I'm closing this issue.

You can ask for help on the framework [google board](https://groups.google.com/forum/#!forum/f3-framework). Maybe somebody there has used this extension already.

**Closed by xfra35** 2016-02-08 10:10 UTC
