### ISSUE TITLE
Cyclic redirect 301/302 caused by trailing slash stripping

### ISSUE THREAD

**Issue by dmig** [bcosca/fatfree#813] opened 2015-04-06 08:50 UTC
This reroute() call https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1368 causes cyclic redirect under following circumstances:
- project dir
  - lib, ui, other dirs
  - public dir
    - public css, js, etc dirs
    - admin dir (symlink actually)
      - admin css, js, etc dirs
    - index.html
    - content.php
    - .htaccess

This structure (public/admin/{css,js,img} and public/{css,js,img}) cannot be changed -- this static content shouldn't be mixed.

Here is .htaccess
```
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !/admin/(css|js|fonts|img)/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^admin.* /content.php [L,QSA]

RewriteRule ^media/content/content.json /content.php [L,QSA]
```
BASE value is autodetected.

Accessing http://project/admin causes a cyclic redirect, which looks like this:
![_2015-04-06_11-45-00](https://cloud.githubusercontent.com/assets/388564/7002384/66bf8594-dc52-11e4-8939-66751458859e.png)

This cycle is caused by two parties:
1. web server (both apache and php internal server do this) kicks to url with trailing slash
2. fatfree kicks to url without trailing slash

So, the question is: why fatfree does this redirect https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1368 ? Isn't this wrong behavior?

**Comment by xfra35** [comment] 2015-04-06 09:22
The line you're referring to is here to prevent duplicate URIs:
* `/admin` is OK
* `/admin/` redirects to `/admin`

There's something missing in your description as you don't explain where the 302 `/ => admin` comes from? Also shouldn't it be `/admin` rather than `admin`?

**Comment by dmig** [comment] 2015-04-06 09:28
This redirect `/ => /admin` is actualy `/admin/ => /admin`, Firefox network monitor shows it like this. This is what framework do in https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1368.
And the second one `/admin => /admin/` is made by webserver internally. As I suppose, reason for that is existing `admin` directory.

**Comment by xfra35** [comment] 2015-04-06 09:50
Your problem comes from the fact that you treat an existing folder as a resource:
* F3 strips trailing slash on its resources
* [mod_dir](http://httpd.apache.org/docs/2.2/mod/mod_dir.html#directoryslash) adds a trailing slash on existing folders

You should disable the second redirect by setting `DirectorySlash Off` in .htaccess

**Comment by dmig** [comment] 2015-04-06 10:46
Ok, and what about PHP internal server? It has same behavior.
I think, `DirectorySlash Off` is not a correct solution.

I suggest making "internal" redirect in such case -- modify $this->hive['URI'] (or it's local copy).

**Comment by xfra35** [comment] 2015-04-06 11:53
How do you obtain the same behaviour with PHP built-in server? I could not manage to reproduce it:

**Structure**
```
admin/
lib/base.php
index.php
```

**index.php**
```php
$f3=require('lib/base.php');
$f3->route('GET /admin',function($f3){
  echo 'admin';
});
$f3->run();
```

**PHP built-in server**
```
php -S localhost:80 index.php
```

**Comment by dmig** [comment] 2015-04-06 11:59
I run php server with command: `php -S localhost:8000 -t public/`, so it can serve static content.

**Comment by xfra35** [comment] 2015-04-06 12:08
No problem either with `php -S localhost:80 -t public/ public/index.php`

**Comment by dmig** [comment] 2015-04-06 12:18
Sorry for misleading you, this doesn't reproduce with current configuration. I faced problem earlier, with different configuration:
- having `index.php` inside `admin/` dir
- and set `BASE=''` explicitlly

Then we get cyclic redirect with internal php server.

**Comment by xfra35** [comment] 2015-04-06 12:39
Well forcing `BASE` is a very bad idea, since it should be autocomputed by the framework. There's surely a better way to accomplish what you're after.

I'm closing this since it looks like an application error rather than a framework bug. Please move on to the [forum](https://groups.google.com/forum/#!forum/f3-framework/) if you're having trouble setting up your app.

**Closed by xfra35** 2015-04-06 12:39 UTC
