### ISSUE TITLE
HTTP_X_FORWARDED_FOR in the ip sniff method

### ISSUE THREAD

**Issue by FrankOssie** [bcosca/fatfree#988] opened 2017-01-12 13:07 UTC
Used by proxy servers and loadbalancers to reference the original ip address

**Comment by exodus4d** [comment] 2017-01-12 18:46
I think this has something to do with: #985

**Comment by xfra35** [comment] 2017-01-12 20:24
Indeed it's a duplicate of #985, which has just been fixed.

**Closed by xfra35** 2017-01-12 20:24 UTC
